# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ingredient(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, weight: float=None):  # noqa: E501
        """Ingredient - a model defined in Swagger

        :param text: The text of this Ingredient.  # noqa: E501
        :type text: str
        :param weight: The weight of this Ingredient.  # noqa: E501
        :type weight: float
        """
        self.swagger_types = {
            'text': str,
            'weight': float
        }

        self.attribute_map = {
            'text': 'text',
            'weight': 'weight'
        }
        self._text = text
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'Ingredient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ingredient of this Ingredient.  # noqa: E501
        :rtype: Ingredient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this Ingredient.

        Ingredient's text  # noqa: E501

        :return: The text of this Ingredient.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Ingredient.

        Ingredient's text  # noqa: E501

        :param text: The text of this Ingredient.
        :type text: str
        """

        self._text = text

    @property
    def weight(self) -> float:
        """Gets the weight of this Ingredient.

        Total weight, g  # noqa: E501

        :return: The weight of this Ingredient.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this Ingredient.

        Total weight, g  # noqa: E501

        :param weight: The weight of this Ingredient.
        :type weight: float
        """

        self._weight = weight
